# Generated by Django 4.1.2 on 2022-11-29 23:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualDailyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_value_date', models.DateField(default=datetime.datetime.today)),
                ('adv_sodium', models.IntegerField(default=0)),
                ('adv_protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adv_water', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adv_K', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adv_phos', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Actual_Daily_Value',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='TargetDailyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdv_sodium', models.IntegerField(default=0)),
                ('tdv_protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tdv_water_male', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tdv_water_female', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tdv_K', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tdv_phos', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Target_Daily_Value',
            },
        ),
        migrations.CreateModel(
            name='TargetSerumLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsl_K', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tsl_phos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tsl_sodium', models.IntegerField(default=0)),
                ('tsl_creatinine_male', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tsl_creatinine_female', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tsl_albumin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tsl_blood_sugar', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Target_Serum_Level',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lastName',
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='height_inches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FoodDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fde_entry_date', models.DateField(default=datetime.datetime.today)),
                ('fde_entry_time', models.TimeField(auto_now=True)),
                ('fde_food_name', models.CharField(max_length=25)),
                ('fde_sodium', models.IntegerField(default=0)),
                ('fde_protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fde_water', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fde_K', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fde_phos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actualDailyValue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthApp.actualdailyvalue')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthApp.client')),
            ],
            options={
                'db_table': 'Food_Diary_Entry',
            },
        ),
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morb_type', models.CharField(max_length=25)),
                ('date_diagnosed', models.DateField(default=datetime.datetime.today)),
                ('notes', models.CharField(max_length=250)),
                ('stage', models.CharField(max_length=10)),
                ('targetDailyValue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthApp.targetdailyvalue')),
                ('targetSerumLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthApp.targetserumlevel')),
            ],
            options={
                'db_table': 'Comorbidity',
            },
        ),
        migrations.CreateModel(
            name='ActualSerumLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asl_date', models.DateField(default=datetime.datetime.today)),
                ('asl_K', models.DecimalField(decimal_places=2, max_digits=8)),
                ('asl_phos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('asl_sodium', models.IntegerField(default=0)),
                ('asl_creatinine', models.DecimalField(decimal_places=2, max_digits=8)),
                ('asl_albumin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('asl_blood_sugar', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthApp.client')),
            ],
            options={
                'db_table': 'Actual_Serum_Level',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='comorbidity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthApp.comorbidity'),
        ),
        migrations.AddField(
            model_name='client',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthApp.person'),
            preserve_default=False,
        ),
    ]
