# Generated by Django 4.1.2 on 2022-11-29 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0002_actualdailyvalue_person_targetdailyvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualserumlevel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comorbidity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.comorbidity'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='targetDailyValue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.targetdailyvalue'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='targetSerumLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.targetserumlevel'),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='actualDailyValue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.actualdailyvalue'),
        ),
        migrations.AlterField(
            model_name='fooddiaryentry',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.client'),
        ),
    ]
