# Generated by Django 4.1.2 on 2022-11-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_alter_actualserumlevel_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddiaryentry',
            name='fde_entry_time',
        ),
        migrations.AlterModelTable(
            name='actualdailyvalue',
            table=None,
        ),
        migrations.AlterModelTable(
            name='actualserumlevel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comorbidity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fooddiaryentry',
            table=None,
        ),
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
        migrations.AlterModelTable(
            name='targetdailyvalue',
            table=None,
        ),
        migrations.AlterModelTable(
            name='targetserumlevel',
            table=None,
        ),
    ]
