# Generated by Django 4.1.2 on 2022-11-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0005_rename_asl_sodium_actualserumlevel_asl_na_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comorbidity',
            name='target_daily_value',
        ),
        migrations.RemoveField(
            model_name='comorbidity',
            name='target_serum_level',
        ),
    ]
