# Generated by Django 4.1.2 on 2022-11-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0006_remove_comorbidity_target_daily_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='comorbidity',
        ),
    ]
