# Generated by Django 4.1.2 on 2022-11-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0007_remove_client_comorbidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualserumlevel',
            name='client',
        ),
    ]
