# Generated by Django 4.1.2 on 2022-11-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0008_remove_actualserumlevel_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddiaryentry',
            name='client',
        ),
    ]
