# Generated by Django 4.1.2 on 2022-11-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0009_remove_fooddiaryentry_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualdailyvalue',
            name='food_diary_entry',
        ),
    ]
