# Generated by Django 4.1.2 on 2022-11-30 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0010_remove_actualdailyvalue_food_diary_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualdailyvalue',
            name='food_diary_entry',
            field=models.ManyToManyField(blank=True, to='healthApp.fooddiaryentry'),
        ),
        migrations.AddField(
            model_name='actualserumlevel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthApp.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='comorbidity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthApp.comorbidity'),
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='target_daily_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthApp.targetdailyvalue'),
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='target_serum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthApp.targetserumlevel'),
        ),
        migrations.AddField(
            model_name='fooddiaryentry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthApp.client'),
        ),
    ]
